-- MySQL Script generated by MySQL Workbench
-- 11/13/16 14:04:37
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brasilclassificados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brasilclassificados` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `brasilclassificados` ;

-- -----------------------------------------------------
-- Table `brasilclassificados`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`usuario` (
  `cod` INT(6) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(20) BINARY NOT NULL,
  `usuario` VARCHAR(50) BINARY NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `nascimento` DATE NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `status` INT(1) NOT NULL,
  `permissao` INT(1) NOT NULL,
  `ip` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasilclassificados`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`categoria` (
  `cod` INT(6) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `thumb` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasilclassificados`.`classificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`classificado` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `tipo` VARCHAR(1) NOT NULL COMMENT 'Venda, troca, doação ou outro',
  `valor` DECIMAL(2) NOT NULL,
  `status` INT(1) NOT NULL,
  `perfil` INT(1) NOT NULL,
  `usuario_cod` INT(6) NOT NULL,
  `categoria_cod` INT(6) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_classificado_usuario1_idx` (`usuario_cod` ASC),
  INDEX `fk_classificado_categoria1_idx` (`categoria_cod` ASC),
  CONSTRAINT `fk_classificado_usuario1`
    FOREIGN KEY (`usuario_cod`)
    REFERENCES `brasilclassificados`.`usuario` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classificado_categoria1`
    FOREIGN KEY (`categoria_cod`)
    REFERENCES `brasilclassificados`.`categoria` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasilclassificados`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`contato` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `assunto` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `data` DATETIME NOT NULL,
  `ip` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasilclassificados`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`comentario` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(500) NOT NULL,
  `data` DATETIME NOT NULL,
  `status` INT(1) NOT NULL,
  `classificado_cod` INT NOT NULL,
  `usuario_cod` INT(6) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_comentario_classificado1_idx` (`classificado_cod` ASC),
  INDEX `fk_comentario_usuario1_idx` (`usuario_cod` ASC),
  CONSTRAINT `fk_comentario_classificado1`
    FOREIGN KEY (`classificado_cod`)
    REFERENCES `brasilclassificados`.`classificado` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_cod`)
    REFERENCES `brasilclassificados`.`usuario` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasilclassificados`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`endereco` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `usuario_cod` INT(6) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_endereco_usuario_idx` (`usuario_cod` ASC),
  CONSTRAINT `fk_endereco_usuario`
    FOREIGN KEY (`usuario_cod`)
    REFERENCES `brasilclassificados`.`usuario` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasilclassificados`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`telefone` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT(1) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `usuario_cod` INT(6) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_telefone_usuario1_idx` (`usuario_cod` ASC),
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`usuario_cod`)
    REFERENCES `brasilclassificados`.`usuario` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasilclassificados`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brasilclassificados`.`imagens` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `imagem` VARCHAR(100) NOT NULL,
  `classificado_cod` INT NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_imagens_classificado1_idx` (`classificado_cod` ASC),
  CONSTRAINT `fk_imagens_classificado1`
    FOREIGN KEY (`classificado_cod`)
    REFERENCES `brasilclassificados`.`classificado` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
